parameters:
  - name: configuration
    type: string
    default: "Release"
  - name: platform
    type: string
    default: ""
  - name: inputArtifactStem
    type: string
    default: ""

jobs:
  - job: OneFuzz
    pool:
      vmImage: windows-2022

    steps:
      - checkout: self
        submodules: false
        clean: true
        fetchDepth: 1
        fetchTags: false

      - download: current
        displayName: Download artifacts
        artifact: build-${{ parameters.platform }}-${{ parameters.configuration }}${{ parameters.inputArtifactStem }}
        patterns: |-
          **/tests/*.FuzzTests/**

      - task: onefuzz-task@0
        inputs:
          onefuzzOSes: Windows
        env:
          onefuzzDropDirectory: $(Pipeline.Workspace)\build-${{ parameters.platform }}-${{ parameters.configuration }}${{ parameters.inputArtifactStem }}\x64\Release\x64\Release\tests
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
