trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:

- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'
- task: NuGetAuthenticate@1
  displayName: 'Authenticate NuGet'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'config'
    nugetConfigPath: './nuget.config'
    includeNuGetOrg: false
  displayName: 'Restore NuGet packages'
- task: MSBuild@1
  inputs:
    solution: 'PowerToys.sln'
    msbuildArchitecture: 'x64'
    configuration: 'Release'
  displayName: 'Build solution'